version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=flyway-postgresql-showcase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
#    volumes:
#      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  flyway-postgresql-showcase:
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      FLYWAY_LICENSE_KEY: PUT_YOUR_LICENSE_KEY_HERE
    depends_on:
      - db
#volumes:
#  db:
#    driver: local