logging:
  pattern.console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}%clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
  file:
    name: flyway-postgresql-showcase.log
  level:
    root: info

spring:
  application:
    name: ^project.artifactId^
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  datasource:
    url: ^flyway.url^
    username: ^flyway.user^
    password: ^flyway.password^
  flyway:
    locations: ^flyway.locations^
    enabled: false # set to true to enable migration on startup
    schemas: ^flyway.schemas^
    baseline-version: 1
    ignore-migration-patterns: "*:ignored"
# swagger-ui custom path
springdoc.swagger-ui.path: /swagger-ui
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      cache:
        time-to-live: "60s"
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
info:
  app:
    name: ^project.name^
    description: ^project.description^
    version: ^project.version^
    encoding: "^project.build.sourceEncoding^"
    build.timestamp: ^maven.build.timestamp^
    java:
      version: "^java.version^"